### ISSUE TITLE
Webserver returned code 429

### ISSUE THREAD

**Issue by Yinchie** [jedisct1/rust-doh#12]
Recently I have been getting the following with dnscrypt-proxy "[ERROR] Webserver returned code 429".

I am not sure what may be the cause of this.
Nothing has been updated or changed on the server except recently newer version(s) of rust-doh.

When I restart rust-doh, it accepts connections again.

**Comment by ibksturm** [comment]
i had the same issue, the final solution was to ruse up the openfile limits on debian system

if your interested how to i will look later this evening at home

**Comment by Yinchie** [comment]
I suppose this?
https://askubuntu.com/questions/1049058/how-to-increase-max-open-files-limit-on-ubuntu-18-04

**Comment by ibksturm** [comment]
exactly 🤩

**Comment by Yinchie** [comment]
Still unable to solve the problem :/

**Comment by jedisct1** [comment]
Try the latest version. It times out stale connections, which can help a lot.
