### ISSUE TITLE
feature request: include systemd service file

### ISSUE THREAD

**Issue by ford--prefect** [jedisct1/rust-doh#15]
It would be convenient to have a bundled service file, e.g. the one suggested in [this tutorial](https://facebookexperimental.github.io/doh-proxy/tutorials/nginx-dohhttpproxy-unbound-centos7.html).
For your convenience:
`**rust-doh.service**
[Unit]
Description=DOH HTTP Proxy on %I
After=syslog.target network.target
Before=nginx.target

[Service]
Type=simple
ExecStart=/bin/doh-httpproxy --upstream-resolver ::1 --level DEBUG --listen-address=::1 --port %I
Restart=always
User=doh-proxy
Group=doh-proxy

[Install]
WantedBy=multi-user.target
`

**Comment by jedisct1** [comment]
I don't use Linux and I don't know much about systemd. So I'd rather keep only the server itself in this repository, and let people who know more about operating systems do the right thing for their specific operating system/distribution.
