### ISSUE TITLE
'tokio-runtime-worker-0' panicked at index out of bounds

### ISSUE THREAD

**Issue by appliedprivacy** [jedisct1/rust-doh#22]
Two rust-doh instances running version 0.1.15 crashed with:

```
thread 'tokio-runtime-worker-0' panicked at 'index out of bounds: 
the len is 0 but the index is 4', doh-proxy-0.1.15/src/dns.rs:9:16
```

They were not running with `RUST_BACKTRACE=1`, but they do now. 

I'll add more information here as it becomes available.

**Comment by jedisct1** [comment]
Is it the real 0.1.15 version installed from `crates.io` or the development code that returns a `400` response on short POST queries?

**Comment by appliedprivacy** [comment]
This is the real 0.1.15 version.

**Comment by jedisct1** [comment]
Try the current git commit, maybe.

**Comment by appliedprivacy** [comment]
Are you planing to tag it in the near future?

**Comment by jedisct1** [comment]
If this fixes the issue you just reported, yes :)

But having either that confirmation or a backtrace from the previous version would be very useful.
