### ISSUE TITLE
return '415 Unsupported Media Type' on unsupported Content-Type

### ISSUE THREAD

**Issue by appliedprivacy** [jedisct1/rust-doh#23]
From comparing the response behavior of rust-doh with [doh-httpproxy](https://github.com/facebookexperimental/doh-proxy) it appears that rust-doh closes the connection instead of returning [415 Unsupported Media Type](https://tools.ietf.org/html/rfc7231#section-6.5.13)
when clients send an unsupported content-type.

Can you confirm that? What do you think about returning 415 in such cases?

thanks!

**Comment by jedisct1** [comment]
If the proxy gets hammered by what is obviously not a DoH client, but rather some random bot or scanner, I'd rather close the connection right away than stay polite so that it keeps trying even more.

That being said, there is apparently nothing in the code that checks the content type in the client request. Only the content itself.

**Comment by appliedprivacy** [comment]
In an environment with a frontend webserver (nginx) and multiple backends handling DoH requests, closing the connection directly instead of returning `415` actually increases unnecessary processing.

nginx will forward the request to the next backend if the first one simply terminated the connection without meaningful response code, instead of giving up after the first one.

This is illustrated by the following log example:
nginx log format: `$status $upstream_status $upstream_addr`

```
415 502, 502, 415 127.0.0.1:3000, 127.0.0.1:3001, [::1]:8082
```


3000 and 3001 are rust-doh instances, 8082 is the backup only backend running doh-httpproxy.

It would be great if that would be configurable so I could tell rust-doh to return 415 and the request would not end up on 3 instances before it stops trying additional instances.

Thank you!

**Comment by jedisct1** [comment]
Can you try the current git code?

**Comment by appliedprivacy** [comment]
We upgraded to current git (217bb90320c65dfa828b3d381abca3c1f697eee0)
and run it for a short while before downgrading again.

Are you enforcing the presence of an accept header? RFC8484 does **not** say there "MUST" be one, right?

>  The DoH client SHOULD include an HTTP Accept request header field to indicate what type of content can be understood in response. 


`Accept: */*`
should also be fine, no?

**Comment by jedisct1** [comment]
What do actual clients send?

**Comment by jedisct1** [comment]
`Content-Type` is now checked instead of `Accept`. But unlike `Accept`, there is no `Content-Type` for `GET` queries.

**Comment by appliedprivacy** [comment]
Enforcing something that is not a MUST in the specification will increase the error rate reduce interoperability unnecessarily, no?

**Comment by jedisct1** [comment]
IETF specifications come with a lot of bureaucracy. They take forever to write, are difficult to update, and are constantly behind the reality. This is blatantly true in the DNS world.

But verifying the `Content-Type` should be enough to avoid forwarding queries from non-DoH clients, so ignoring `Accept` is fine.

**Comment by appliedprivacy** [comment]
What is the motivation to reject requests that worked fine before?

**Comment by jedisct1** [comment]
Blocking junk as soon as possible in the chain. If a query doesn't come from a DoH client, don't waste time on it.

**Comment by appliedprivacy** [comment]
How do you know it does not come from a DoH client?

**Comment by jedisct1** [comment]
If it's expecting a HTML page as a response, it's very unlikely to be a DoH client :)

**Comment by appliedprivacy** [comment]
Why do you think it is expecting an HTML page?

**Comment by jedisct1** [comment]
Bots don't harvest web servers to get DNS responses.
