### ISSUE TITLE
Cloudflared client - Content-type: application/dns-udpwireformat

### ISSUE THREAD

**Issue by pengelana** [jedisct1/rust-doh#24]
[cloudflared ](https://developers.cloudflare.com/1.1.1.1/dns-over-https/cloudflared-proxy/) release: cloudflared version 2019.6.0 (built 2019-06-04-1650 UTC)

rust-doh release: 0.1.17 

~~~
clouldflared send:  "Content-type: application/dns-udpwireformat"
rust-doh reply   :  "415 Unsupported Media Type"
~~~

related to this [commit](https://github.com/jedisct1/rust-doh/commit/224609ea9bb2a3b12376e294946af87d24da2564)? 

ref: https://tools.ietf.org/id/draft-ietf-doh-dns-over-https-05.html#rfc.section.7.1

**Comment by jedisct1** [comment]
That was changed to [`application-dns/message`](https://tools.ietf.org/html/rfc8484#section-6) more than a year ago, and this is what went into the RFC.

Cloudflared should be updated.

**Comment by jedisct1** [comment]
I sent them a pull request [here](https://github.com/cloudflare/cloudflared/pull/108).

**Comment by Glandos** [comment]
I know that you're right, but in this case, the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) could be easily applied:
> Be conservative in what you do, be liberal in what you accept from others (often reworded as "Be conservative in what you send, be liberal in what you accept").

So `rust-doh` can still accept the old `Content-type`, and issues a log line or something.

**Comment by jedisct1** [comment]
I'd rather avoid keeping hacks for broken software forever. A year is a reasonable time frame.
