### ISSUE TITLE
rust-doh return 406 Not Acceptable

### ISSUE THREAD

**Issue by pengelana** [jedisct1/rust-doh#25]
We keep seeing `406 Not Acceptable` from rust-doh when client send `HTTP GET`:

rust-doh: 0.1.17

`user-agent: dnscrypt-proxy`
`HTTP Method: GET`
`Request URI Path: dns-query`
`Request URI Parameter: ct=`
`Request URI Parameter: dns-query=`

**Comment by jedisct1** [comment]
Ah, that's bad.

And my server only accepts GET queries, so it should have been unaccessible for the past few days :(

The new version should fix it.

Thanks!

**Comment by pengelana** [comment]
Just upgrade to rust-doh 0.1.18, all good!

Thanks!
