### ISSUE TITLE
ipv6 upstream servers possibly don't work

### ISSUE THREAD

**Issue by Dieff** [jedisct1/rust-doh#27]
When I try to use a v6 address for `--server-address`, I only get 500s back from `doh-proxy`.
I attempted to use both Google's public DNS (2001:4860:4860::8888) and a listener on localhost (::1), both caused 500s. Using a `doh-proxy` compiled from latest commit here.

## Reproduce
1. Grab a machine with dual ipv4 and ipv6 addresses.
2. Check with `dig` that you can query a public v6 server, such as Google's.
`$ dig @2001:4860:4860:0:0:0:0:8888 github.com`
3. Run `/doh-proxy -u [2001:4860:4860:0:0:0:0:8888]:53`. This should setup `doh-query` to use the same upstream DNS server we just tested.
4. Query `doh-proxy` for a name. I used the [libcurl doh client](https://github.com/curl/doh). Receive a 500 error in reply.

```
$ ./doh github.com http://localhost:3000/dns-query
Probe for A got response: 500
Probe for AAAA got response: 500
```

Frankly both ipv6 and doh are somewhat new to me. Feel free to close the issue if you can't reproduce, it may be a problem with my network.

## System info
```
$ uname -ra
Linux  5.2.0-arch2-1-ARCH #1 SMP PREEMPT Mon Jul 8 18:18:54 UTC 2019 x86_64 GNU/Linux

$ cargo --version
cargo 1.37.0-nightly (4c1fa54d1 2019-06-24)

$ rustc --version
rustc 1.38.0-nightly (78ca1bda3 2019-07-08)

$ ip a s
// snip
3: wlp59s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether bc:a8:a6:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    inet 100.66.xxx.xxx/20 brd 100.66.xxx.255 scope global dynamic noprefixroute wlp59s0
       valid_lft 34699sec preferred_lft 34699sec
    inet6 2610:48:xxxx:xxxx::xxxx/128 scope global dynamic noprefixroute
       valid_lft 78384sec preferred_lft 45984sec
    inet6 fe80::825e:2247:765d:337/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

```

**Comment by pengelana** [comment]
try to add --listend-address and --local-bind-address, the default value is for v4

'const LISTEN_ADDRESS: &str = "127.0.0.1:3000";'
'const LOCAL_BIND_ADDRESS: &str = "0.0.0.0:0";'

doh-proxy --listen-address [::1]:3000  --server-address [2401:c080:1400:4fe6:5400:1ff:fed0:2ae3]:53 --local-bind-address [::]:0

**Comment by pengelana** [comment]
- without local-bind-address:

`# ./doh-proxy -u [2001:4860:4860:0:0:0:0:8888]:53`

~~~
# ./doh google.com http://localhost:3000/dns-query
Probe for A got response: 500
Probe for AAAA got response: 500
~~~

- with local-bind-address [::]:0

`# ./doh-proxy -u [2001:4860:4860:0:0:0:0:8888]:53 -b [::]:0`

~~~
# ./doh google.com http://localhost:3000/dns-query
google.com from http://localhost:3000/dns-query
TTL: 70 seconds
A: 74.125.68.101
A: 74.125.68.102
A: 74.125.68.139
A: 74.125.68.100
A: 74.125.68.113
A: 74.125.68.138
~~~

**Comment by Dieff** [comment]
That is my issue. Thanks.

I think the only change to make here would be #11 so it would have been easier to figure out what went wrong.

**Comment by pengelana** [comment]
#37
