### ISSUE TITLE
nginx reverse proxy example config

### ISSUE THREAD

**Issue by kpcyrd** [jedisct1/rust-doh#28]
I think this would be a common usecase, having this documented would be awesome.

**Comment by jedisct1** [comment]
I added an [operational recommendations](https://github.com/jedisct1/rust-doh#operational-recommendations) section as well as an [example usage with nginx](https://github.com/jedisct1/rust-doh#example-usage-with-nginx) section.

But I'm not sure what to say here. People deploying DoH probably already have web services set up, so it's just about adding a new path with the DoH proxy as an upstream.
