### ISSUE TITLE
Distributing doh-proxy in debian

### ISSUE THREAD

**Issue by kpcyrd** [jedisct1/rust-doh#29]
I'm considering uploading doh-proxy to debian. Would that work for you? Also if there's anything you want me to keep in mind while packaging this please let me know.

**Comment by jedisct1** [comment]
I don't use Debian, but of course, having packages would be very useful for people who don't want to install Rust just for this. Go ahead :)

Maybe you want to include TLS support (the `tls` feature), though?

**Comment by monperrus** [comment]
Great, looking forward to doh-proxy on debian!
