### ISSUE TITLE
Read configuration from toml file

### ISSUE THREAD

**Issue by kpcyrd** [jedisct1/rust-doh#30]
To make  #29 easier, do you think it would be possible to support reading a configuration from a toml file? Something like:
```
doh-proxy -c /etc/doh-proxy.toml
```

**Comment by jedisct1** [comment]
There isn't a lot of options, and the long options are pretty self-explanatory, so a configuration file seems overkill.

Maybe once the proxy gains more features and becomes unmanageable with simple command-line options, but it isn't the case now, and hopefully won't be the case in a near future :)
