### ISSUE TITLE
How can I get the Certificate hashes value?

### ISSUE THREAD

**Issue by IceCodeNew** [jedisct1/rust-doh#36]
I've just set up a rust-doh server successfully. As I'm filling a table [here](https://dnscrypt.info/stamps/) to get an encoded DNS Stamp, the _**Certificate hash (SHA256)**_ blank has confused me.

As I can see there are two comma-separated hashes of the certificate have been encoded in Cloudflare's DNS Stamp, I have no idea about how they are generated nor which certificate's fingerprint could match one of them.

**Comment by IceCodeNew** [comment]
I tried to run the command **`$ openssl x509 -noout -fingerprint -sha256 -inform pem -in cert.pem`** . Here the output is as long as either part of the certificate hashes of Cloudflare's DNS Stamp.
But I'm not sure if I'm on the right path ;-P

#### What I get
> SHA256 Fingerprint=89:45:15:CF:52:7B:8C:6E:4D:B7:79:DB:12:78:B6:35:84:0C:07:CC:08:59:4E:BE:CA:B2:77:6C:3C:B5:1D:31

#### The example to compare
> 10d93c9864a521f3065cc3a522509c2afabb01581cad9c6d8e89fdd75f9ea747,eb7525f88f0d9458f81a995019bfd34cb89ccdc957e7b0ef315f10f897638118

![](https://i.loli.net/2019/08/15/fOtgn7KQ5o8hEzq.png)

**Comment by jedisct1** [comment]
Hi,

You can create a stamp without the hashes first, check that everything works as expected, then use the following command to print the hashes:

```sh
dnscrypt-proxy -show-certs 
```

**Comment by jedisct1** [comment]
And if you're using Let's Encrypt, that would be the hashes of the Let's Encrypt certificates signing your certificates.

**Comment by IceCodeNew** [comment]
> Hi,
> 
> You can create a stamp without the hashes first, check that everything works as expected, then use the following command to print the hashes:
> 
> ```shell
> dnscrypt-proxy -show-certs 
> ```

### $ `./dnscrypt-proxy -show-certs`
```
flag provided but not defined: -show-certs
Usage of ./dnscrypt-proxy:
  -check
        check the configuration file and exit
  -child
        Invokes program as a child process
  -config string
        Path to the configuration file (default "dnscrypt-proxy.toml")
  -json
        output list as JSON
  -list
        print the list of available resolvers for the enabled filters
  -list-all
        print the complete list of available resolvers, ignoring filters
  -logfile string
        Write logs to file
  -loglevel value
        Log level (0-6) (default 2)
  -netprobe-timeout int
        Override the netprobe timeout (default 60)
  -pidfile string
        If specified, write pid to file.
  -resolve string
        resolve a name using system libraries
  -service string
        Control the system service: ["start" "stop" "restart" "install" "uninstall"]
  -syslog
        Send logs to the local system logger (Eventlog on Windows, syslog on Unix)
  -version
        print current proxy version
```

### $ `./dnscrypt-proxy -version`
```
2.0.25
```

### $ `uname -a`
```
Linux ubuntu-s-1vcpu-1gb-sgp1-01 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

---

Thanks for reply so soon.
Here I got a _FLAG NOT DEFINED_ error, any idea?

**Comment by IceCodeNew** [comment]
> And if you're using Let's Encrypt, that would be the hashes of the Let's Encrypt certificates signing your certificates.

If I didn't get you wrong, there could be loads of DoH servers sharing the same certificate hash, as long as they use the certificate signed by _Let's Encrypt Authority X3_ root certificate to handle the HTTPS traffic. Am I right?

Also it is difficult for me to find out what the hashes of the Let's Encrypt certificates are. I think they might lay somewhere in this [statement](https://letsencrypt.org/documents/isrg-cps-v2.6/) but just fail to spot them.

**Comment by jedisct1** [comment]
Correct. But this will prevent MITM attacks using certificates signed by a different authority, as what recently happened in Kazakhstan.

Ah indeed, that feature was introduced after version `2.0.25` was release.

You can do this, then:

```sh
env export SHOW_CERTS=1 dnscrypt-proxy -loglevel 0
```

**Comment by IceCodeNew** [comment]
> Correct. But this will prevent MITM attacks using certificates signed by a different authority, as what recently happened in Kazakhstan.

Got it, that hash will bring the advantage in DNSCrypt protocol to the DoH protocol! I'd say that's an awesome part in the design of DNS Stamp.

---

> Ah indeed, that feature was introduced after version `2.0.25` was release.
> 
> You can do this, then:
> 
> ```shell
> env SHOW_CERTS=1 dnscrypt-proxy -loglevel 0
> ```

### $ `env SHOW_CERTS=1`
```
…
OLDPWD=/root
_=/usr/bin/env
SHOW_CERTS=1
```

### $ `./dnscrypt-proxy -loglevel 0`
`[2019-08-15 18:54:59] [FATAL] listen udp 127.0.0.1:53: bind: address already in use`

### $ `./dnscrypt-proxy -service stop`
```
[2019-08-15 18:55:17] [NOTICE] dnscrypt-proxy 2.0.25
[2019-08-15 18:55:17] [NOTICE] Service stopped
```

### $ `./dnscrypt-proxy -loglevel 0`
`(there just nothing)`

---

Have I done something wrong?

**Comment by jedisct1** [comment]
Maybe you changed `log_file = ...` or `use_syslog =` in the configuration file and the logs are being written elsewhere?

**Comment by IceCodeNew** [comment]
Negative, I actually keep these flags of logging feature disabled, just as how they are set in the example configuration file.

**Comment by IceCodeNew** [comment]
I've just built the _dnscrypt-proxy_ from source code. Thus I make the client support _-show-certs_ flag.
But to my surprise, the command **`./dnscrypt-proxy -show-certs`** doesn't turn out any results.

#### $ `./dnscrypt-proxy -show-certs`
`(just nothing to show)`

#### $ `./dnscrypt-proxy -list`
```
mydomain.tld
quad9-dnscrypt-ip4-filter-pri
cloudflare
```

#### $ `tail dnscrypt-proxy.toml`
```
## Optional, local, static list of additional servers
## Mostly useful for testing your own servers.

[static]

  # [static.'google']
  # stamp = 'sdns://AgUAAAAAAAAAAAAOZG5zLmdvb2dsZS5jb20NL2V4cGVyaW1lbnRhbA'
  [static.'mydomain.tld']
  stamp = 'sdns://AgcAAAAAAAAAD*************************************************F1ZXJ5'
```

**Comment by IceCodeNew** [comment]
Got an idea. Just check your domain on the [SSL Labs site](https://www.ssllabs.com/ssltest/index.html), and the result page will show the hash of the intermediate certificate (In this case it's _Let's Encrypt Authority X3_).
> Subject `Let's Encrypt Authority X3`
> Fingerprint SHA256: `25847d668eb4f04fdd40b12b6b0740c567da7d024308eb6c2c96fe41d9de218d`

Also, you can check it at [here](https://crt.sh/?id=15706126). Which give you more detail about the certificate so that you are less likely to get confused about which certificate's info you really need.

**Comment by jedisct1** [comment]
Not having any output is unexpected.

Maybe the configuration file has `log_level` raised? By default, it's set to `2`.

**Comment by IceCodeNew** [comment]
> Got an idea. Just check your domain on the [SSL Labs site](https://www.ssllabs.com/ssltest/index.html), and the result page will show the hash of the intermediate certificate (In this case it's _Let's Encrypt Authority X3_).
> 
> > Subject `Let's Encrypt Authority X3`
> > Fingerprint SHA256: `25847d668eb4f04fdd40b12b6b0740c567da7d024308eb6c2c96fe41d9de218d`
> 
> Also, you can check it at [here](https://crt.sh/?id=15706126). Which give you more detail about the certificate so that you are less likely to get confused about which certificate's info you really need.

After adding the hash `25847d668eb4f04fdd40b12b6b0740c567da7d024308eb6c2c96fe41d9de218d` to the blank and paste the new generated DNS stamp to the configuration file, everything got break :-(
![](https://i.loli.net/2019/08/15/5ZBD7TmGnMjJwp8.png)

**Comment by IceCodeNew** [comment]
> Not having any output is unexpected.
> 
> Maybe the configuration file has `log_level` raised? By default, it's set to `2`.

You are right, after uncommenting that line and adjusting the log_level to 0, **`$ ./dnscrypt-proxy -show-certs`** will show the detail about _Advertised cert_. And that's exactly what I need.
Thank you again for everything you've done ;-)
