### ISSUE TITLE
bind to IPv6 socket if connecting to IPv6 socket

### ISSUE THREAD

**Issue by mherrb** [jedisct1/rust-doh#37]
Hi,

I tried to use doh-proxy connecting to my unbound server on localhost:53.

./.cargo/bin/doh-proxy  -u localhost:53

Unfortunatly this setup produces 500 internal server error on all queries.

As I'm running a dual-stack host, the -u argument resolves to [::1]:53.

Tracing the process shows that it is trying to talk to [::1]:53 from a socket bound to 0.0.0.0:0.

So using -b [::0]:0 fixes the proxy. 

But I think that if using ipv6 for -u, one should switch to IPv6 for the default bind address too.

**Comment by jedisct1** [comment]
It should be the case now. Thanks for suggesting this!

**Comment by mherrb** [comment]
Thanks. Works as expected now!
