### ISSUE TITLE
server error: Incomplete

### ISSUE THREAD

**Issue by cstrotm** [jedisct1/rust-doh#5]
Hi,

I'm trying rust-doh with dnscrypt-proxy (and Firefox 60 DoH).

With both clients, I get the error message `server error: Incomplete` for every DoH request

```
#  /root/.cargo/bin/doh-proxy -u [::1]:53
Listening on http://127.0.0.1:3000
server error: Incomplete
server error: Incomplete
server error: Incomplete
server error: Incomplete
server error: Incomplete
server error: Incomplete
server error: Incomplete
server error: Incomplete
```

The webserver logs look sane:
```
185.xx.xx.xx - - [29/May/2018:15:07:29 +0200] "POST /dns-query HTTP/2.0" 502 16                                                                                                                                                              
185.xx.xx.xx - - [29/May/2018:15:07:29 +0200] "GET /dns-query?body=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&random_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/2.0" 502 16                
```

The webserver is a caddy (https://caddyserver.com/)

Any hints how to troubleshoot this issue?

**Comment by jedisct1** [comment]
The DoH drafts replaced `body` with `dns` a long time ago, which suggests that you tried with an old Firefox version that didn't implement the current specifications.

**Comment by ibksturm** [comment]
hi there

same problem here (version 0.1.8) (doh-ibksturm)

from time to time the server crashes and i have to restart the service on debian 

now i updatet to version 0.1.9, is there some updates to handle the body issue in the url request of old firefox version? or any tipps or tricks or a work around? i think i will wrote a script & cronjob every minute, that will check the journalctrl output of doh-proxy again this server errors and restart the service

**Comment by jedisct1** [comment]
Can you try to get a backtrace when the server crashes?

**Comment by ibksturm** [comment]
stupid question, what is a backtrace? do you mean the login file or something like that?

**Comment by ibksturm** [comment]
ok, server was crushed right now, on the logfile journal -u doh-proxy was written

server error: incomplete

the systemd service is still running on as staus running

ao i restartet the service right now

**Comment by jedisct1** [comment]
So, it stops responding queries after printing "Incomplete", but the process still runs?

**Comment by jedisct1** [comment]
Can you check if `2d03cf4b55832bd41f17ddd137b8cbb172739dcc` fixes it?

**Comment by ibksturm** [comment]
a) yeas thats what i mean

b) what do you mean wirh this hash? sorry i dont understand it :(

**Comment by ibksturm** [comment]
update 

```
.....
Aug 24 21:40:06 nas2 doh-proxy[11354]: server error: Incomplete
Aug 24 21:40:06 nas2 doh-proxy[11354]: server error: Incomplete
Aug 24 21:43:11 nas2 doh-proxy[11354]: server error: Incomplete
Aug 24 21:43:11 nas2 doh-proxy[11354]: server error: Incomplete
Aug 24 21:49:49 nas2 doh-proxy[11354]: server error: Incomplete
.....
```

aaand

```
[2018-08-24 21:51:03] [NOTICE] Source [opennic.md] loaded
[2018-08-24 21:51:03] [NOTICE] dnscrypt-proxy 2.0.16
[2018-08-24 21:51:03] [NOTICE] Loading the set of cloaking rules from [/etc/dnscrypt-proxy/cloaking-rules.txt]
[2018-08-24 21:51:03] [NOTICE] Now listening to 127.0.2.1:855 [UDP]
[2018-08-24 21:51:03] [NOTICE] Now listening to 127.0.2.1:855 [TCP]
[2018-08-24 21:51:03] [NOTICE] Now listening to [::1]:855 [UDP]
[2018-08-24 21:51:03] [NOTICE] Now listening to [::1]:855 [TCP]
[2018-08-24 21:51:04] [ERROR] Get https://ibksturm.synology.me:853/dns-query?body=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&ct=&dns=yv4BAAABAAAAAAABAAACAAEAACkQAAAAgAAAAA&random_padding=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
[2018-08-24 21:51:04] [NOTICE] dnscrypt-proxy is waiting for at least one server to be reachable
[2018-08-24 21:51:14] [NOTICE] [doh-ibksturm] OK (DoH) - rtt: 7ms
[2018-08-24 21:51:14] [NOTICE] Server with the lowest initial latency: doh-ibksturm (rtt: 7ms)

```
doh-ibksturm ist still running, you did a good job frank :+1: 

if i'll see something other issues i will write you

**Comment by ibksturm** [comment]
update, server crushed today i think 3 times.. and with no logs entrys on journalctrl... creepi thing

so i've got the idear to change the powerunit where the bananpi take it's electricity

i will tell you if theres something change

**Comment by publicarray** [comment]
Hi unfortunately my doh server seems to restart (due to docker health check failing) on my GCP instance see the dips at https://dns.seby.io/status.html Unfortunately I don’t have reliable Internet for this week so I might need some time to get a backtrace. The vultr node is still running v0.1.7 which works reliably.

**Comment by ibksturm** [comment]
hi guys, my solutions for the crashes is a cronjob, where the doh-ibksturm and ibksturm (for cert change) starts every hour new
